language: node_js
node_js: stable

install: true

branches:
  only:
  - master

before_script:
- git config --global user.name "travis"
- git config --global user.email "travis@miantiao.me"

script:
- git push -f https://$GITHUB_KEY@github.com/$TRAVIS_REPO_SLUG.git `npm version patch -m "%s [ci skip]"`
- git push -f https://$GITHUB_KEY@github.com/$TRAVIS_REPO_SLUG.git HEAD:master
