name: Release

on:
  push:
    master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: yarn
          registry-url: https://registry.npmjs.org

      - name: purge cdn
        run: node ./helper/purge.js